{{- if .Values.secret.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "cli-release-server.secretName" . | quote }}
  labels:
    {{- include "cli-release-server.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.secret.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.secret.externalSecret.secretStore.name | quote }}
    kind: {{ .Values.secret.externalSecret.secretStore.kind | quote }}
  target:
    name: {{ include "cli-release-server.secretName" . | quote }}
    creationPolicy: Owner
  data:
    {{- range $key, $remoteKey := .Values.secret.externalSecret.remoteKeys }}
    - secretKey: {{ $key | quote }}
      remoteRef:
        key: {{ $remoteKey | quote }}
    {{- end }}
{{- end }}
