{{- if and .Values.config.releaseGithubRepository .Values.secret.create (not .Values.secret.existingSecret) (not .Values.secret.externalSecret.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cli-release-server.secretName" . }}
  labels:
    {{- include "cli-release-server.labels" . | nindent 4 }}
type: Opaque
data:
  CLI_RELEASE_GITHUB_TOKEN: {{ .Values.secret.values.releaseGithubToken | b64enc | quote }}
{{- end }}
